import scroll from "./modules/scroll.js";
import sectionNavigation from "./modules/scroll-animation.js";
import activeFaq from "./modules/faq-animation.js";
import activeList from "./modules/list-animation.js";
import initModal from "./modules/modal.js";
import actionTooltip from "./modules/tooltip.js";
import dropDownMenuAction from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initOperationSchedule from "./modules/operating-schedule.js";
import initAnimalsFetch from "./modules/animals-fetch.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

scroll();
sectionNavigation();
activeFaq();
activeList();
initModal();
actionTooltip();
dropDownMenuAction();
initMenuMobile();
initOperationSchedule();
initAnimalsFetch();
initFetchBitcoin();